version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8081}:8081"
      - "${WS_PORT:-8082}:8082"
    environment:
      - PORT=8081
      - WS_PORT=8082 